# Dados de conexão com o PostgreSQL
spring.datasource.url=${BANCO_URL:jdbc:postgresql://localhost:5432/ceuma}
spring.datasource.username=${BANCO_USUARIO:postgres}
spring.datasource.password=${BANCO_SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Dados do desafio de RA
aluno.nome=${NOME_ALUNO}
aluno.ra=${RA_ALUNO}
