# Dados de conexão com o PostgreSQL
spring.datasource.url=${BANCO_URL:jdbc:postgresql://localhost:5432/ceuma}
spring.datasource.username=${BANCO_USUARIO:postgres}
spring.datasource.password=${BANCO_SENHA}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
